services:
  movies_database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${MOVIES_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MOVIES_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MOVIES_POSTGRES_DB}
    volumes:
      - db_movies:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  movies-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      MOVIES_SPRING_DATASOURCE_URL: jdbc:postgresql://movies_database:5432/movies
      MOVIES_POSTGRES_USER: ${MOVIES_POSTGRES_USER}
      MOVIES_POSTGRES_PASSWORD: ${MOVIES_POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - backend
    depends_on:
      movies_database:
        condition: service_started

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    command:
      - --changelog-file=classpath:db/changelog/db.changelog-master.yaml
      - --driver=org.postgresql.Driver
      - --url=${MOVIES_SPRING_DATASOURCE_URL}
      - --username=${MOVIES_POSTGRES_USER}
      - --password=${MOVIES_POSTGRES_PASSWORD}
      - update
    depends_on:
      movies_database:
        condition: service_started
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    networks:
      - backend

networks:
  backend:
  movies_network:

volumes:
  db_movies:
  migrations: